version: 0.2
phases:
 install: # Install AWS cli, kubectl (needed for Helm) and Helm
  commands:
   - echo Logging to AWS ECR…
   — aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y5m5n1r0

 pre_build: # Add kubeconfig to access to EKS cluster
  commands:
   — echo Update kubeconfig…
   — aws eks update-kubeconfig — name ${EKS_NAME} — region ${REGION}
   — kubectl version
 build: # Build Docker image and tag it with the commit sha
  commands:
   — echo Building docker image…
   — docker build -t leandroportocci .
   — docker tag leandroportocci:latest public.ecr.aws/y5m5n1r0/leandroportocci:latest
 post_build: # Push the Docker image to the ECR
  commands:
   — echo Pushing ECR…
   — docker push public.ecr.aws/y5m5n1r0/leandroportocci:latest
   - echo Rollout new version
   - echo kubectl set image deployment/$DEPLOYMENT_NAME [container name]=$REPOSITORY_URI:$IMAGE_TAG
   — “kubectl set image deployment/$DEPLOYMENT_NAME [container name]=$REPOSITORY_URI:$IMAGE_TAG”
