version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y5m5n1r0
      - REPOSITORY_URI=public.ecr.aws/y5m5n1r0/leandroportocci
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t leandroportocci .
      - docker tag leandroportocci:latest public.ecr.aws/y5m5n1r0/leandroportocci:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push public.ecr.aws/y5m5n1r0/leandroportocci:latest
      - echo Writing image definitions file...
      - printf '[{"name":"leandroportocci","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: 
      - imagedefinitions.json
